### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'default_factory'

### ISSUE THREAD

**Issue by galeo** [orf/django-debug-toolbar-template-timings#35]
This issue may be introduced by #33, check [here](https://github.com/orf/django-debug-toolbar-template-timings/pull/33#issuecomment-364296258) for details.

**Comment by orf** [comment]
I think I fixed this in https://github.com/orf/django-debug-toolbar-template-timings/commit/aedce9d964656b6b8f1e15b5430d37d34ee014f8, could you confirm?

**Comment by DemonVex** [comment]
Yes, It works.

**Comment by galeo** [comment]
Thanks. I can confirm it was fixed.

**Comment by orf** [comment]
Awesome, I will push a new release tonight. Thanks for testing!

**Comment by galeo** [comment]
Sorry, I could not find the new release on PyPI. Has it been pushed?

**Comment by orf** [comment]
`0.9` has just been released, I guess I forgot to push a release! My apologies 👍

**Comment by galeo** [comment]
Thanks! 👍
